### PR TITLE
RT-74 Fix krux custom test runner to work with django 1.8

### PR DESCRIPTION
**Pull request by ghost**
Merged code from original repo

### CODE REVIEW

**Comment by arijitdey** [comment]
:-1: 
The PR is raised is against master and not the RT-26-django-upgrade branch. If this is blocking from running tests on the new django branch, why do we need to merge this to master?

**Comment by ghost** [comment]
@arijitdey I've just synced code from original repo to krux forked

**Comment by arijitdey** [comment]
@alekseyC64 Can we do this in a branch? I know you have taken care of backward compatibility.

**Comment by plathrop** [comment]
Since this is just a merge from upstream, +1 LGTM.

**Comment by ghost** [comment]
yes, this is the only merge from upstream

**Pull request merged**
